// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1.2 (64-bit)
// Version: 2022.1.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module system_v_frmbuf_wr_0_0_MultiPixStream2Bytes (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        img_dout,
        img_num_data_valid,
        img_fifo_cap,
        img_empty_n,
        img_read,
        bytePlanes_plane01_din,
        bytePlanes_plane01_num_data_valid,
        bytePlanes_plane01_fifo_cap,
        bytePlanes_plane01_full_n,
        bytePlanes_plane01_write,
        bytePlanes_plane12_din,
        bytePlanes_plane12_num_data_valid,
        bytePlanes_plane12_fifo_cap,
        bytePlanes_plane12_full_n,
        bytePlanes_plane12_write,
        Height_dout,
        Height_num_data_valid,
        Height_fifo_cap,
        Height_empty_n,
        Height_read,
        WidthInBytes_dout,
        WidthInBytes_num_data_valid,
        WidthInBytes_fifo_cap,
        WidthInBytes_empty_n,
        WidthInBytes_read,
        VideoFormat_dout,
        VideoFormat_num_data_valid,
        VideoFormat_fifo_cap,
        VideoFormat_empty_n,
        VideoFormat_read,
        WidthInBytes_c_din,
        WidthInBytes_c_num_data_valid,
        WidthInBytes_c_fifo_cap,
        WidthInBytes_c_full_n,
        WidthInBytes_c_write,
        height_c_din,
        height_c_num_data_valid,
        height_c_fifo_cap,
        height_c_full_n,
        height_c_write,
        video_format_c_din,
        video_format_c_num_data_valid,
        video_format_c_fifo_cap,
        video_format_c_full_n,
        video_format_c_write
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [23:0] img_dout;
input  [1:0] img_num_data_valid;
input  [1:0] img_fifo_cap;
input   img_empty_n;
output   img_read;
output  [63:0] bytePlanes_plane01_din;
input  [10:0] bytePlanes_plane01_num_data_valid;
input  [10:0] bytePlanes_plane01_fifo_cap;
input   bytePlanes_plane01_full_n;
output   bytePlanes_plane01_write;
output  [63:0] bytePlanes_plane12_din;
input  [10:0] bytePlanes_plane12_num_data_valid;
input  [10:0] bytePlanes_plane12_fifo_cap;
input   bytePlanes_plane12_full_n;
output   bytePlanes_plane12_write;
input  [11:0] Height_dout;
input  [1:0] Height_num_data_valid;
input  [1:0] Height_fifo_cap;
input   Height_empty_n;
output   Height_read;
input  [14:0] WidthInBytes_dout;
input  [2:0] WidthInBytes_num_data_valid;
input  [2:0] WidthInBytes_fifo_cap;
input   WidthInBytes_empty_n;
output   WidthInBytes_read;
input  [5:0] VideoFormat_dout;
input  [2:0] VideoFormat_num_data_valid;
input  [2:0] VideoFormat_fifo_cap;
input   VideoFormat_empty_n;
output   VideoFormat_read;
output  [14:0] WidthInBytes_c_din;
input  [1:0] WidthInBytes_c_num_data_valid;
input  [1:0] WidthInBytes_c_fifo_cap;
input   WidthInBytes_c_full_n;
output   WidthInBytes_c_write;
output  [11:0] height_c_din;
input  [1:0] height_c_num_data_valid;
input  [1:0] height_c_fifo_cap;
input   height_c_full_n;
output   height_c_write;
output  [5:0] video_format_c_din;
input  [1:0] video_format_c_num_data_valid;
input  [1:0] video_format_c_fifo_cap;
input   video_format_c_full_n;
output   video_format_c_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg img_read;
reg[63:0] bytePlanes_plane01_din;
reg bytePlanes_plane01_write;
reg bytePlanes_plane12_write;
reg Height_read;
reg WidthInBytes_read;
reg VideoFormat_read;
reg WidthInBytes_c_write;
reg height_c_write;
reg video_format_c_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    Height_blk_n;
reg    WidthInBytes_blk_n;
reg    VideoFormat_blk_n;
reg    WidthInBytes_c_blk_n;
reg    height_c_blk_n;
reg    video_format_c_blk_n;
wire   [5:0] VideoFormat_read_read_fu_186_p2;
reg   [5:0] VideoFormat_read_reg_658;
reg   [11:0] Height_read_reg_662;
wire   [12:0] trunc_ln571_1_fu_319_p4;
reg   [12:0] trunc_ln571_1_reg_688;
wire   [0:0] icmp_ln576_fu_333_p2;
reg   [0:0] icmp_ln576_reg_693;
wire   [12:0] sub209_fu_347_p2;
reg   [12:0] sub209_reg_698;
wire   [0:0] cmp212_fu_353_p2;
reg   [0:0] cmp212_reg_703;
wire   [0:0] icmp11_fu_369_p2;
reg   [0:0] icmp11_reg_708;
wire   [0:0] cmp212_2_fu_375_p2;
reg   [0:0] cmp212_2_reg_713;
wire   [0:0] icmp14_fu_391_p2;
reg   [0:0] icmp14_reg_718;
wire   [0:0] cmp212_4_fu_397_p2;
reg   [0:0] cmp212_4_reg_723;
wire   [0:0] cmp212_5_fu_403_p2;
reg   [0:0] cmp212_5_reg_728;
wire   [0:0] cmp212_6_fu_409_p2;
reg   [0:0] cmp212_6_reg_733;
wire   [0:0] notlhs_fu_415_p2;
reg   [0:0] notlhs_reg_738;
wire   [12:0] trunc_ln534_1_fu_436_p4;
reg   [12:0] trunc_ln534_1_reg_762;
wire   [0:0] grp_fu_299_p2;
reg   [0:0] icmp_ln539_reg_767;
wire   [12:0] sub118_fu_458_p2;
reg   [12:0] sub118_reg_772;
wire   [0:0] cmp121_fu_464_p2;
reg   [0:0] cmp121_reg_777;
wire   [0:0] icmp8_fu_480_p2;
reg   [0:0] icmp8_reg_782;
wire   [0:0] cmp121_2_fu_486_p2;
reg   [0:0] cmp121_2_reg_787;
wire   [12:0] trunc_ln496_1_fu_507_p4;
reg   [12:0] trunc_ln496_1_reg_811;
reg   [0:0] icmp_ln501_reg_816;
wire   [12:0] sub40_fu_529_p2;
reg   [12:0] sub40_reg_821;
wire   [0:0] cmp43_fu_535_p2;
reg   [0:0] cmp43_reg_826;
wire   [0:0] icmp_fu_551_p2;
reg   [0:0] icmp_reg_831;
wire   [0:0] cmp43_2_fu_557_p2;
reg   [0:0] cmp43_2_reg_836;
reg   [7:0] p_0_0_0_0_0_7136_lcssa157_load_reg_844;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln583_fu_575_p2;
reg   [7:0] p_0_1_0_0_0_7145_lcssa160_load_reg_849;
wire   [0:0] brmerge79_fu_598_p2;
reg   [0:0] brmerge79_reg_854;
reg   [7:0] p_0_0_0_0_0258_3108_lcssa121_load_reg_862;
wire   [0:0] icmp_ln546_fu_611_p2;
reg   [7:0] p_0_1_0_0_0260_3112_lcssa124_load_reg_867;
reg   [7:0] p_0_0_0_0_0266_383_lcssa97_load_reg_875;
wire   [0:0] icmp_ln508_fu_636_p2;
reg   [7:0] p_0_1_0_0_0268_389_lcssa100_load_reg_880;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_ap_start;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_ap_done;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_ap_idle;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_ap_ready;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_img_read;
wire   [63:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_bytePlanes_plane12_din;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_bytePlanes_plane12_write;
wire   [63:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_bytePlanes_plane01_din;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_bytePlanes_plane01_write;
wire   [7:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_p_0_1_0_0_0_7144_out;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_p_0_1_0_0_0_7144_out_ap_vld;
wire   [7:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_p_0_0_0_0_0_7135_out;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_p_0_0_0_0_0_7135_out_ap_vld;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_ap_start;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_ap_done;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_ap_idle;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_ap_ready;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_img_read;
wire   [63:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_bytePlanes_plane01_din;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_bytePlanes_plane01_write;
wire   [7:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_p_0_1_0_0_0260_3111_out;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_p_0_1_0_0_0260_3111_out_ap_vld;
wire   [7:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_p_0_0_0_0_0258_3107_out;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_p_0_0_0_0_0258_3107_out_ap_vld;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_ap_start;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_ap_done;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_ap_idle;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_ap_ready;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_img_read;
wire   [63:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_bytePlanes_plane01_din;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_bytePlanes_plane01_write;
wire   [7:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_p_0_1_0_0_0268_388_out;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_p_0_1_0_0_0268_388_out_ap_vld;
wire   [7:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_p_0_0_0_0_0266_382_out;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_p_0_0_0_0_0266_382_out_ap_vld;
reg    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [7:0] p_0_1_0_0_0_7145_lcssa160_fu_158;
reg   [7:0] p_0_0_0_0_0_7136_lcssa157_fu_154;
reg    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg   [7:0] p_0_1_0_0_0260_3112_lcssa124_fu_170;
reg   [7:0] p_0_0_0_0_0258_3108_lcssa121_fu_166;
reg    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg   [7:0] p_0_1_0_0_0268_389_lcssa100_fu_182;
reg   [7:0] p_0_0_0_0_0266_383_lcssa97_fu_178;
reg   [11:0] y_2_fu_150;
wire   [11:0] y_8_fu_580_p2;
reg    ap_block_state1;
reg   [11:0] y_1_fu_162;
wire   [11:0] y_6_fu_616_p2;
reg   [11:0] y_fu_174;
wire   [11:0] y_4_fu_641_p2;
wire   [1:0] grp_fu_289_p4;
wire   [15:0] zext_ln571_fu_309_p1;
wire   [15:0] add_ln571_fu_313_p2;
wire   [2:0] remainPix_4_fu_305_p1;
wire   [3:0] zext_ln574_fu_329_p1;
wire   [3:0] remainPix_5_fu_339_p3;
wire   [2:0] tmp_2_fu_359_p4;
wire   [1:0] tmp_3_fu_381_p4;
wire   [15:0] zext_ln534_fu_426_p1;
wire   [15:0] add_ln534_fu_430_p2;
wire   [2:0] zext_ln537_fu_446_p1;
wire   [2:0] remainPix_3_fu_450_p3;
wire   [1:0] tmp_1_fu_470_p4;
wire   [15:0] zext_ln496_fu_497_p1;
wire   [15:0] add_ln496_fu_501_p2;
wire   [2:0] zext_ln499_fu_517_p1;
wire   [2:0] remainPix_1_fu_521_p3;
wire   [1:0] tmp_fu_541_p4;
wire   [0:0] trunc_ln583_fu_571_p1;
wire   [0:0] tobool_not_fu_592_p2;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 8'd1;
#0 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_ap_start_reg = 1'b0;
#0 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_ap_start_reg = 1'b0;
#0 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_ap_start_reg = 1'b0;
end

system_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_ap_start),
    .ap_done(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_ap_done),
    .ap_idle(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_ap_idle),
    .ap_ready(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_ap_ready),
    .img_dout(img_dout),
    .img_num_data_valid(2'd0),
    .img_fifo_cap(2'd0),
    .img_empty_n(img_empty_n),
    .img_read(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_img_read),
    .p_0_1_0_0_0_7145_lcssa160(p_0_1_0_0_0_7145_lcssa160_load_reg_849),
    .p_0_0_0_0_0_7136_lcssa157(p_0_0_0_0_0_7136_lcssa157_load_reg_844),
    .trunc_ln571_1(trunc_ln571_1_reg_688),
    .bytePlanes_plane12_din(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_bytePlanes_plane12_din),
    .bytePlanes_plane12_num_data_valid(11'd0),
    .bytePlanes_plane12_fifo_cap(11'd0),
    .bytePlanes_plane12_full_n(bytePlanes_plane12_full_n),
    .bytePlanes_plane12_write(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_bytePlanes_plane12_write),
    .bytePlanes_plane01_din(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_bytePlanes_plane01_din),
    .bytePlanes_plane01_num_data_valid(11'd0),
    .bytePlanes_plane01_fifo_cap(11'd0),
    .bytePlanes_plane01_full_n(bytePlanes_plane01_full_n),
    .bytePlanes_plane01_write(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_bytePlanes_plane01_write),
    .brmerge79(brmerge79_reg_854),
    .icmp_ln576(icmp_ln576_reg_693),
    .cmp212_6(cmp212_6_reg_733),
    .cmp212_5(cmp212_5_reg_728),
    .cmp212_4(cmp212_4_reg_723),
    .cmp212_3(icmp14_reg_718),
    .cmp212_2(cmp212_2_reg_713),
    .cmp212_1(icmp11_reg_708),
    .sub209_cast58(sub209_reg_698),
    .cmp212(cmp212_reg_703),
    .p_0_1_0_0_0_7144_out(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_p_0_1_0_0_0_7144_out),
    .p_0_1_0_0_0_7144_out_ap_vld(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_p_0_1_0_0_0_7144_out_ap_vld),
    .p_0_0_0_0_0_7135_out(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_p_0_0_0_0_0_7135_out),
    .p_0_0_0_0_0_7135_out_ap_vld(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_p_0_0_0_0_0_7135_out_ap_vld)
);

system_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_ap_start),
    .ap_done(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_ap_done),
    .ap_idle(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_ap_idle),
    .ap_ready(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_ap_ready),
    .img_dout(img_dout),
    .img_num_data_valid(2'd0),
    .img_fifo_cap(2'd0),
    .img_empty_n(img_empty_n),
    .img_read(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_img_read),
    .p_0_1_0_0_0260_3112_lcssa124(p_0_1_0_0_0260_3112_lcssa124_load_reg_867),
    .p_0_0_0_0_0258_3108_lcssa121(p_0_0_0_0_0258_3108_lcssa121_load_reg_862),
    .trunc_ln534_1(trunc_ln534_1_reg_762),
    .bytePlanes_plane01_din(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_bytePlanes_plane01_din),
    .bytePlanes_plane01_num_data_valid(11'd0),
    .bytePlanes_plane01_fifo_cap(11'd0),
    .bytePlanes_plane01_full_n(bytePlanes_plane01_full_n),
    .bytePlanes_plane01_write(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_bytePlanes_plane01_write),
    .icmp_ln539(icmp_ln539_reg_767),
    .cmp121_2(cmp121_2_reg_787),
    .cmp121_1(icmp8_reg_782),
    .sub118_cast57(sub118_reg_772),
    .cmp121(cmp121_reg_777),
    .p_0_1_0_0_0260_3111_out(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_p_0_1_0_0_0260_3111_out),
    .p_0_1_0_0_0260_3111_out_ap_vld(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_p_0_1_0_0_0260_3111_out_ap_vld),
    .p_0_0_0_0_0258_3107_out(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_p_0_0_0_0_0258_3107_out),
    .p_0_0_0_0_0258_3107_out_ap_vld(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_p_0_0_0_0_0258_3107_out_ap_vld)
);

system_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_ap_start),
    .ap_done(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_ap_done),
    .ap_idle(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_ap_idle),
    .ap_ready(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_ap_ready),
    .img_dout(img_dout),
    .img_num_data_valid(2'd0),
    .img_fifo_cap(2'd0),
    .img_empty_n(img_empty_n),
    .img_read(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_img_read),
    .p_0_1_0_0_0268_389_lcssa100(p_0_1_0_0_0268_389_lcssa100_load_reg_880),
    .p_0_0_0_0_0266_383_lcssa97(p_0_0_0_0_0266_383_lcssa97_load_reg_875),
    .trunc_ln496_1(trunc_ln496_1_reg_811),
    .bytePlanes_plane01_din(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_bytePlanes_plane01_din),
    .bytePlanes_plane01_num_data_valid(11'd0),
    .bytePlanes_plane01_fifo_cap(11'd0),
    .bytePlanes_plane01_full_n(bytePlanes_plane01_full_n),
    .bytePlanes_plane01_write(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_bytePlanes_plane01_write),
    .icmp_ln501(icmp_ln501_reg_816),
    .cmp43_2(cmp43_2_reg_836),
    .cmp43_1(icmp_reg_831),
    .sub40_cast56(sub40_reg_821),
    .cmp43(cmp43_reg_826),
    .p_0_1_0_0_0268_388_out(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_p_0_1_0_0_0268_388_out),
    .p_0_1_0_0_0268_388_out_ap_vld(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_p_0_1_0_0_0268_388_out_ap_vld),
    .p_0_0_0_0_0266_382_out(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_p_0_0_0_0_0266_382_out),
    .p_0_0_0_0_0266_382_out_ap_vld(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_p_0_0_0_0_0266_382_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & ((((((icmp_ln583_fu_575_p2 == 1'd1) & (6'd18 == VideoFormat_read_reg_658)) | ((icmp_ln583_fu_575_p2 == 1'd1) & (6'd19 == VideoFormat_read_reg_658))) | (~(6'd28 == VideoFormat_read_reg_658) & ~(6'd18 == VideoFormat_read_reg_658) & ~(6'd19 == VideoFormat_read_reg_658) & (icmp_ln508_fu_636_p2 == 1'd1))) | ((icmp_ln546_fu_611_p2 == 1'd1) & (6'd28 == VideoFormat_read_reg_658))) | (~(6'd12 == VideoFormat_read_reg_658) & ~(6'd28 == VideoFormat_read_reg_658) & ~(6'd18 == VideoFormat_read_reg_658) & ~(6'd19 == VideoFormat_read_reg_658))))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_ap_start_reg <= 1'b1;
        end else if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_ap_ready == 1'b1)) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_ap_start_reg <= 1'b1;
        end else if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_ap_ready == 1'b1)) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_ap_start_reg <= 1'b1;
        end else if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_ap_ready == 1'b1)) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1) & (6'd28 == VideoFormat_read_read_fu_186_p2))) begin
        y_1_fu_162 <= 12'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln546_fu_611_p2 == 1'd0) & (6'd28 == VideoFormat_read_reg_658))) begin
        y_1_fu_162 <= y_6_fu_616_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1) & ((6'd18 == VideoFormat_read_read_fu_186_p2) | (6'd19 == VideoFormat_read_read_fu_186_p2)))) begin
        y_2_fu_150 <= 12'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (((icmp_ln583_fu_575_p2 == 1'd0) & (6'd18 == VideoFormat_read_reg_658)) | ((icmp_ln583_fu_575_p2 == 1'd0) & (6'd19 == VideoFormat_read_reg_658))))) begin
        y_2_fu_150 <= y_8_fu_580_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1) & (6'd12 == VideoFormat_read_read_fu_186_p2))) begin
        y_fu_174 <= 12'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln508_fu_636_p2 == 1'd0) & (6'd12 == VideoFormat_read_reg_658))) begin
        y_fu_174 <= y_4_fu_641_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        Height_read_reg_662 <= Height_dout;
        VideoFormat_read_reg_658 <= VideoFormat_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (((icmp_ln583_fu_575_p2 == 1'd0) & (6'd18 == VideoFormat_read_reg_658)) | ((icmp_ln583_fu_575_p2 == 1'd0) & (6'd19 == VideoFormat_read_reg_658))))) begin
        brmerge79_reg_854 <= brmerge79_fu_598_p2;
        p_0_0_0_0_0_7136_lcssa157_load_reg_844 <= p_0_0_0_0_0_7136_lcssa157_fu_154;
        p_0_1_0_0_0_7145_lcssa160_load_reg_849 <= p_0_1_0_0_0_7145_lcssa160_fu_158;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (6'd28 == VideoFormat_read_read_fu_186_p2))) begin
        cmp121_2_reg_787 <= cmp121_2_fu_486_p2;
        cmp121_reg_777 <= cmp121_fu_464_p2;
        icmp8_reg_782 <= icmp8_fu_480_p2;
        icmp_ln539_reg_767 <= grp_fu_299_p2;
        sub118_reg_772 <= sub118_fu_458_p2;
        trunc_ln534_1_reg_762 <= {{add_ln534_fu_430_p2[15:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & ((6'd18 == VideoFormat_read_read_fu_186_p2) | (6'd19 == VideoFormat_read_read_fu_186_p2)))) begin
        cmp212_2_reg_713 <= cmp212_2_fu_375_p2;
        cmp212_4_reg_723 <= cmp212_4_fu_397_p2;
        cmp212_5_reg_728 <= cmp212_5_fu_403_p2;
        cmp212_6_reg_733 <= cmp212_6_fu_409_p2;
        cmp212_reg_703 <= cmp212_fu_353_p2;
        icmp11_reg_708 <= icmp11_fu_369_p2;
        icmp14_reg_718 <= icmp14_fu_391_p2;
        icmp_ln576_reg_693 <= icmp_ln576_fu_333_p2;
        notlhs_reg_738 <= notlhs_fu_415_p2;
        sub209_reg_698 <= sub209_fu_347_p2;
        trunc_ln571_1_reg_688 <= {{add_ln571_fu_313_p2[15:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (6'd12 == VideoFormat_read_read_fu_186_p2))) begin
        cmp43_2_reg_836 <= cmp43_2_fu_557_p2;
        cmp43_reg_826 <= cmp43_fu_535_p2;
        icmp_ln501_reg_816 <= grp_fu_299_p2;
        icmp_reg_831 <= icmp_fu_551_p2;
        sub40_reg_821 <= sub40_fu_529_p2;
        trunc_ln496_1_reg_811 <= {{add_ln496_fu_501_p2[15:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_p_0_0_0_0_0258_3107_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        p_0_0_0_0_0258_3108_lcssa121_fu_166 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_p_0_0_0_0_0258_3107_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln546_fu_611_p2 == 1'd0) & (6'd28 == VideoFormat_read_reg_658))) begin
        p_0_0_0_0_0258_3108_lcssa121_load_reg_862 <= p_0_0_0_0_0258_3108_lcssa121_fu_166;
        p_0_1_0_0_0260_3112_lcssa124_load_reg_867 <= p_0_1_0_0_0260_3112_lcssa124_fu_170;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_p_0_0_0_0_0266_382_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        p_0_0_0_0_0266_383_lcssa97_fu_178 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_p_0_0_0_0_0266_382_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln508_fu_636_p2 == 1'd0) & (6'd12 == VideoFormat_read_reg_658))) begin
        p_0_0_0_0_0266_383_lcssa97_load_reg_875 <= p_0_0_0_0_0266_383_lcssa97_fu_178;
        p_0_1_0_0_0268_389_lcssa100_load_reg_880 <= p_0_1_0_0_0268_389_lcssa100_fu_182;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_p_0_0_0_0_0_7135_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_0_0_0_7136_lcssa157_fu_154 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_p_0_0_0_0_0_7135_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_p_0_1_0_0_0260_3111_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        p_0_1_0_0_0260_3112_lcssa124_fu_170 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_p_0_1_0_0_0260_3111_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_p_0_1_0_0_0268_388_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        p_0_1_0_0_0268_389_lcssa100_fu_182 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_p_0_1_0_0_0268_388_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_p_0_1_0_0_0_7144_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_1_0_0_0_7145_lcssa160_fu_158 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_p_0_1_0_0_0_7144_out;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        Height_blk_n = Height_empty_n;
    end else begin
        Height_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        Height_read = 1'b1;
    end else begin
        Height_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        VideoFormat_blk_n = VideoFormat_empty_n;
    end else begin
        VideoFormat_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        VideoFormat_read = 1'b1;
    end else begin
        VideoFormat_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthInBytes_blk_n = WidthInBytes_empty_n;
    end else begin
        WidthInBytes_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthInBytes_c_blk_n = WidthInBytes_c_full_n;
    end else begin
        WidthInBytes_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthInBytes_c_write = 1'b1;
    end else begin
        WidthInBytes_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthInBytes_read = 1'b1;
    end else begin
        WidthInBytes_read = 1'b0;
    end
end

always @ (*) begin
    if (((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & ((((((icmp_ln583_fu_575_p2 == 1'd1) & (6'd18 == VideoFormat_read_reg_658)) | ((icmp_ln583_fu_575_p2 == 1'd1) & (6'd19 == VideoFormat_read_reg_658))) | (~(6'd28 == VideoFormat_read_reg_658) & ~(6'd18 == VideoFormat_read_reg_658) & ~(6'd19 == VideoFormat_read_reg_658) & (icmp_ln508_fu_636_p2 == 1'd1))) | ((icmp_ln546_fu_611_p2 == 1'd1) & (6'd28 == VideoFormat_read_reg_658))) | (~(6'd12 == VideoFormat_read_reg_658) & ~(6'd28 == VideoFormat_read_reg_658) & ~(6'd18 == VideoFormat_read_reg_658) & ~(6'd19 == VideoFormat_read_reg_658))))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & ((((((icmp_ln583_fu_575_p2 == 1'd1) & (6'd18 == VideoFormat_read_reg_658)) | ((icmp_ln583_fu_575_p2 == 1'd1) & (6'd19 == VideoFormat_read_reg_658))) | (~(6'd28 == VideoFormat_read_reg_658) & ~(6'd18 == VideoFormat_read_reg_658) & ~(6'd19 == VideoFormat_read_reg_658) & (icmp_ln508_fu_636_p2 == 1'd1))) | ((icmp_ln546_fu_611_p2 == 1'd1) & (6'd28 == VideoFormat_read_reg_658))) | (~(6'd12 == VideoFormat_read_reg_658) & ~(6'd28 == VideoFormat_read_reg_658) & ~(6'd18 == VideoFormat_read_reg_658) & ~(6'd19 == VideoFormat_read_reg_658))))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        bytePlanes_plane01_din = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_bytePlanes_plane01_din;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        bytePlanes_plane01_din = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_bytePlanes_plane01_din;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        bytePlanes_plane01_din = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_bytePlanes_plane01_din;
    end else begin
        bytePlanes_plane01_din = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_bytePlanes_plane01_din;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        bytePlanes_plane01_write = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_bytePlanes_plane01_write;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        bytePlanes_plane01_write = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_bytePlanes_plane01_write;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        bytePlanes_plane01_write = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_bytePlanes_plane01_write;
    end else begin
        bytePlanes_plane01_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        bytePlanes_plane12_write = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_bytePlanes_plane12_write;
    end else begin
        bytePlanes_plane12_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_c_blk_n = height_c_full_n;
    end else begin
        height_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_c_write = 1'b1;
    end else begin
        height_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        img_read = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_img_read;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        img_read = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_img_read;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        img_read = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_img_read;
    end else begin
        img_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        video_format_c_blk_n = video_format_c_full_n;
    end else begin
        video_format_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        video_format_c_write = 1'b1;
    end else begin
        video_format_c_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & ((((((icmp_ln583_fu_575_p2 == 1'd1) & (6'd18 == VideoFormat_read_reg_658)) | ((icmp_ln583_fu_575_p2 == 1'd1) & (6'd19 == VideoFormat_read_reg_658))) | (~(6'd28 == VideoFormat_read_reg_658) & ~(6'd18 == VideoFormat_read_reg_658) & ~(6'd19 == VideoFormat_read_reg_658) & (icmp_ln508_fu_636_p2 == 1'd1))) | ((icmp_ln546_fu_611_p2 == 1'd1) & (6'd28 == VideoFormat_read_reg_658))) | (~(6'd12 == VideoFormat_read_reg_658) & ~(6'd28 == VideoFormat_read_reg_658) & ~(6'd18 == VideoFormat_read_reg_658) & ~(6'd19 == VideoFormat_read_reg_658))))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln508_fu_636_p2 == 1'd0) & (6'd12 == VideoFormat_read_reg_658))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln546_fu_611_p2 == 1'd0) & (6'd28 == VideoFormat_read_reg_658))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign VideoFormat_read_read_fu_186_p2 = VideoFormat_dout;

assign WidthInBytes_c_din = WidthInBytes_dout;

assign add_ln496_fu_501_p2 = (zext_ln496_fu_497_p1 + 16'd7);

assign add_ln534_fu_430_p2 = (zext_ln534_fu_426_p1 + 16'd7);

assign add_ln571_fu_313_p2 = (zext_ln571_fu_309_p1 + 16'd7);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_block_state1 = ((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign brmerge79_fu_598_p2 = (tobool_not_fu_592_p2 | notlhs_reg_738);

assign bytePlanes_plane12_din = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_bytePlanes_plane12_din;

assign cmp121_2_fu_486_p2 = ((remainPix_3_fu_450_p3 > 3'd2) ? 1'b1 : 1'b0);

assign cmp121_fu_464_p2 = ((remainPix_3_fu_450_p3 != 3'd0) ? 1'b1 : 1'b0);

assign cmp212_2_fu_375_p2 = ((remainPix_5_fu_339_p3 > 4'd2) ? 1'b1 : 1'b0);

assign cmp212_4_fu_397_p2 = ((remainPix_5_fu_339_p3 > 4'd4) ? 1'b1 : 1'b0);

assign cmp212_5_fu_403_p2 = ((remainPix_5_fu_339_p3 > 4'd5) ? 1'b1 : 1'b0);

assign cmp212_6_fu_409_p2 = ((remainPix_5_fu_339_p3 > 4'd6) ? 1'b1 : 1'b0);

assign cmp212_fu_353_p2 = ((remainPix_5_fu_339_p3 != 4'd0) ? 1'b1 : 1'b0);

assign cmp43_2_fu_557_p2 = ((remainPix_1_fu_521_p3 > 3'd2) ? 1'b1 : 1'b0);

assign cmp43_fu_535_p2 = ((remainPix_1_fu_521_p3 != 3'd0) ? 1'b1 : 1'b0);

assign grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_ap_start = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_271_ap_start_reg;

assign grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_ap_start = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_253_ap_start_reg;

assign grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_ap_start = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_228_ap_start_reg;

assign grp_fu_289_p4 = {{WidthInBytes_dout[2:1]}};

assign grp_fu_299_p2 = ((grp_fu_289_p4 == 2'd0) ? 1'b1 : 1'b0);

assign height_c_din = Height_dout;

assign icmp11_fu_369_p2 = ((tmp_2_fu_359_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp14_fu_391_p2 = ((tmp_3_fu_381_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp8_fu_480_p2 = ((tmp_1_fu_470_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_fu_551_p2 = ((tmp_fu_541_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln508_fu_636_p2 = ((y_fu_174 == Height_read_reg_662) ? 1'b1 : 1'b0);

assign icmp_ln546_fu_611_p2 = ((y_1_fu_162 == Height_read_reg_662) ? 1'b1 : 1'b0);

assign icmp_ln576_fu_333_p2 = ((remainPix_4_fu_305_p1 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln583_fu_575_p2 = ((y_2_fu_150 == Height_read_reg_662) ? 1'b1 : 1'b0);

assign notlhs_fu_415_p2 = ((VideoFormat_dout != 6'd19) ? 1'b1 : 1'b0);

assign remainPix_1_fu_521_p3 = ((grp_fu_299_p2[0:0] == 1'b1) ? 3'd4 : zext_ln499_fu_517_p1);

assign remainPix_3_fu_450_p3 = ((grp_fu_299_p2[0:0] == 1'b1) ? 3'd4 : zext_ln537_fu_446_p1);

assign remainPix_4_fu_305_p1 = WidthInBytes_dout[2:0];

assign remainPix_5_fu_339_p3 = ((icmp_ln576_fu_333_p2[0:0] == 1'b1) ? 4'd8 : zext_ln574_fu_329_p1);

assign sub118_fu_458_p2 = ($signed(trunc_ln534_1_fu_436_p4) + $signed(13'd8191));

assign sub209_fu_347_p2 = ($signed(trunc_ln571_1_fu_319_p4) + $signed(13'd8191));

assign sub40_fu_529_p2 = ($signed(trunc_ln496_1_fu_507_p4) + $signed(13'd8191));

assign tmp_1_fu_470_p4 = {{remainPix_3_fu_450_p3[2:1]}};

assign tmp_2_fu_359_p4 = {{remainPix_5_fu_339_p3[3:1]}};

assign tmp_3_fu_381_p4 = {{remainPix_5_fu_339_p3[3:2]}};

assign tmp_fu_541_p4 = {{remainPix_1_fu_521_p3[2:1]}};

assign tobool_not_fu_592_p2 = (trunc_ln583_fu_571_p1 ^ 1'd1);

assign trunc_ln496_1_fu_507_p4 = {{add_ln496_fu_501_p2[15:3]}};

assign trunc_ln534_1_fu_436_p4 = {{add_ln534_fu_430_p2[15:3]}};

assign trunc_ln571_1_fu_319_p4 = {{add_ln571_fu_313_p2[15:3]}};

assign trunc_ln583_fu_571_p1 = y_2_fu_150[0:0];

assign video_format_c_din = VideoFormat_dout;

assign y_4_fu_641_p2 = (y_fu_174 + 12'd1);

assign y_6_fu_616_p2 = (y_1_fu_162 + 12'd1);

assign y_8_fu_580_p2 = (y_2_fu_150 + 12'd1);

assign zext_ln496_fu_497_p1 = WidthInBytes_dout;

assign zext_ln499_fu_517_p1 = grp_fu_289_p4;

assign zext_ln534_fu_426_p1 = WidthInBytes_dout;

assign zext_ln537_fu_446_p1 = grp_fu_289_p4;

assign zext_ln571_fu_309_p1 = WidthInBytes_dout;

assign zext_ln574_fu_329_p1 = remainPix_4_fu_305_p1;

endmodule //system_v_frmbuf_wr_0_0_MultiPixStream2Bytes
