<AutoPilot:project xmlns:AutoPilot="com.autoesl.autopilot.project" projectType="C/C++" top="v_frmbuf_wr" name="prj">
    <includePaths/>
    <libraryFlag/>
    <solutions>
        <solution name="sol" status=""/>
    </solutions>
    <files>
        <file name="/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls/hls_video_undistort.h" sc="0" tb="false" cflags="-I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls -I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls/hls_video_types.h" sc="0" tb="false" cflags="-I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls -I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls/hls_video_stereobm.h" sc="0" tb="false" cflags="-I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls -I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls/hls_video_mem.h" sc="0" tb="false" cflags="-I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls -I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls/hls_video_io.h" sc="0" tb="false" cflags="-I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls -I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls/hls_video_imgproc.h" sc="0" tb="false" cflags="-I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls -I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls/hls_video_imgbase.h" sc="0" tb="false" cflags="-I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls -I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls/hls_video_hough.h" sc="0" tb="false" cflags="-I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls -I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls/hls_video_histogram.h" sc="0" tb="false" cflags="-I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls -I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls/hls_video_harris.h" sc="0" tb="false" cflags="-I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls -I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls/hls_video_haar.h" sc="0" tb="false" cflags="-I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls -I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls/hls_video_fast.h" sc="0" tb="false" cflags="-I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls -I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls/hls_video_core.h" sc="0" tb="false" cflags="-I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls -I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls/hls_video_arithm.h" sc="0" tb="false" cflags="-I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls -I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls/hls_axi_io.h" sc="0" tb="false" cflags="-I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls -I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls_opencv.h" sc="0" tb="false" cflags="-I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls -I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls_video.h" sc="0" tb="false" cflags="-I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls -I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/v_frmbuf_wr.h" sc="0" tb="false" cflags="-I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls -I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/v_frmbuf_wr.cpp" sc="0" tb="false" cflags="-I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls -I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src" csimflags="" blackbox="false"/>
        <file name="/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/v_frmbuf_wr_config.h" sc="0" tb="false" cflags="-I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src/hls -I/home/sgdh/Zybo-Z7-HW/proj/Zybo-Z7-HW.gen/sources_1/bd/system/ip/system_v_frmbuf_wr_0_0/src" csimflags="" blackbox="false"/>
    </files>
</AutoPilot:project>

